# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [10.16.0, 10.x, 12.x, 14.x, 16.x]
        mysql-version: [mysql:5.7, mysql:8.0, mariadb:10.6]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.1
        with:
          node-version:  ${{ matrix.node-version }}
      - name: Set up MySQL
        uses: uses: shogo82148/actions-setup-mysql@v1
        with: 
          mysql-version: ${{ matrix.mysql-version }} 
          root-password: test
      - run: npm install
      - name: Wait mysql server is ready
        run: node wait-mysql-up.js
      - run: node setup.js
      - run: node benchmark-select-1000.js
