# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # 10.16.0, 10.x, 12.x, 14.x, 
        node-version: [16.x]

    # services:
    #   mariadb:
    #     image: mariadb:latest
    #     ports:
    #       - 3306
    #     env:
    #       MYSQL_USER: user
    #       MYSQL_PASSWORD: password
    #       MYSQL_DATABASE: test
    #       MYSQL_ROOT_PASSWORD: password
    #     options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.1
        with:
          node-version:  ${{ matrix.node-version }}
      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql root password: test
      - run: npm install
      - name: Wait mysql server is ready
        run: node wait-mysql-up.js
      - run: node setup.js
      - run: node benchmark.js
